URL := https://masie_web.apps.nsidc.org/pub/DATASETS/NOAA/G02135/south/daily/geotiff/2002/02_Feb/S_20020222_extent_v3.0.tif
FILE_NAME := S_20020222_extent_v3.0.tif

#FILE_NAME := https://masie_web.apps.nsidc.org/pub/DATASETS/NOAA/G02135/south/daily/geotiff/2002/02_Feb/S_20020222_extent_v3.0.tif

$(FILE_NAME) :
	wget -q -O $(FILE_NAME) $(URL)
